### ISSUE TITLE
Ratings in History list

### ISSUE THREAD

**Issue by JasonLG1979** [JeffHoogland/qAndora#14]
I'm trying to figure out a way to indicate the song rating in the history list in a good way without making it too busy. Ideally I'd overlay a small icon over the album cover like Pithos does but currently it looks like this. What are your thoughts on this?
![rating](https://cloud.githubusercontent.com/assets/6667703/6170478/9f694b78-b29a-11e4-9c47-7e5c9f72ca37.png)

**Comment by JeffHoogland** [comment]
Seems fine.
