### ISSUE TITLE
Error from pthyon when loaded.

### ISSUE THREAD

**Issue by ShapeShifter499** [JeffHoogland/qAndora#17]
When I tried loading this I got this error. I don't know much programing so I'm not sure why this happens.

```
[lance@Arch-chromebook qAndora]$ python qAndora.py
  File "qAndora.py", line 323
    if self.albumartpath == 'images/albumart.png': 
                                                  ^
TabError: inconsistent use of tabs and spaces in indentation
[lance@Arch-chromebook qAndora]$
```

**Comment by JeffHoogland** [comment]
Can't reproduce this here on Ubuntu 14.04. Fresh git clone and running with python: http://i.imgur.com/y7FGZQa.png

Can you try running the application with python 2 and see if that works? I know python 3 is the default in arch.

**Comment by JasonLG1979** [comment]
I get the exact same error message if I try to run qAndora with python 3. So I'm going to say this bug is invalid, and run qAndora with python 2.
