### ISSUE TITLE
Any interest in ReplayGain? 

### ISSUE THREAD

**Issue by JasonLG1979** [JeffHoogland/qAndora#18]
Pandora sends ReplayGain info in the form of a dB value. I'm working on an implementation that takes that value, and if it's a negative applies it to the volume. Basically "loud songs" are turned down a bit and "Quiet songs" are allowed full scale. (No compression or limiting is applied since nothing is ever boasted) The net effect is that the apparent volume between songs is leveled out a bit. It's not extremely useful for stations that contain all modern recordings of the same genre because they tend to have about the same apparent volume but for mixed stations it's nice. I have a classic rock station that plays stuff from the 60's - late 80's and it levels them out nicely.

**Comment by JeffHoogland** [comment]
Seems great.
