### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by JasonLG1979** [JeffHoogland/qAndora#19]
If so I've managed to figure out how to toggle the the explicit content filter in Pandora. I've also managed to throw a UI checkbox for it in the pref window.  The explicit content filter setting is account wide. So if one client sets it, it effects all clients.

Basically it works like this:
The setting 'lives' in/at Pandora so we don't save anything in the prefs. At start up we set the checkbox to unchecked. After we login we ask Pandora if it's enabled and Pandora returns a Boolean. We use that  Boolean to decide the state of the checkbox and from there we use the checkbox as a trigger to send enable and disable calls to Pandora to toggle the filter state.

**Comment by JeffHoogland** [comment]
I'm still maintaining this project in terms of fixing bugs for existing features yes. Not really planning to make any future improvements though as I am dedicating my open source time to other projects at the moment.

That sounds like a reasonable improvement and if you have the know-how to make it happen please make a pull request with the required changes and I will review, test, and merge them if they are functional.

**Comment by JasonLG1979** [comment]
Right on. I'm still testing it myself. I've also hacked up pandora.py so that you get a 128 mp3 for the high quality setting. I'm still testing them both out. When I get everything sorted I'll I make a pull request. I'm also working on adding the feature to Pithos. 

Long run In the effort to learn python 3 and PyQT5 I'm going to attempt a port/rewrite one of these days.

**Comment by JeffHoogland** [comment]
Python 3 isn't that much different. Qt5 is on my eventual TODO list to dive into.

**Comment by JasonLG1979** [comment]
Oh another thing. The filter doesn't, of course take effect until the next playlist.
